AWSTemplateFormatVersion: 2010-09-09
Description: |
  Devops Lab
Parameters:
  VPCCidrBlock:
    Description: "The IPv4 CIDR block for the VPC"
    Type: String
    Default: "10.0.0.0/16"
  VPCName:
    Description: "The Name tag for the VPC"
    Type: String
    Default: "Devops-VPC"
  PublicInternetGatewayName:
    Description: "The Name tag for the Internet Gateway"
    Type: String
    Default: "Devops-Internet-Gateway"
  PublicRouteTableName:
    Description: "The Name tag for the Public Route Table"
    Type: String
    Default: "Public-Route-Table"
  PublicSubnetCidrBlock:
    Description: "The IPv4 CIDR block for the Public Subnet"
    Type: String
    Default: "10.0.0.0/24"
  PublicSubnetName:
    Description: "The Name tag for the Public Subnet"
    Type: String
    Default: "Public-Subnet"
  PublicSecurityGroupName:
    Description: "The Name tag and Group Name for the Public Security Group"
    Type: String
    Default: "Devops-Public-Security-Group"
  PublicSecurityIngressUserIP:
    Description: "The specific allowed source IP address (in CIDR format) for SSH and Ping access to the public EC2 instance"
    Type: String
    Default: "115.73.227.29/32"
  KeyPairName:
    Description: "The name of the EC2 Key Pair to be created"
    Type: String
    Default: "Devops-Key-Pair"
  KeyPairPublicKey:
    Description: "The SSH public key material (ssh-rsa) used to access the EC2 instances"
    Type: String
    Default: >
      ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDyF0nd30kDBg0SxUCF0nPi14v6Tm3TCTj22pCp2RZ3mzJCyvQ8ToXVoHGf/XOQnEh2cyL52bt0aEbudeBTWwSM3yE78UoUW8odNu00DUtjCTu9Ve2GspLEJl7tE4iveqpAbc0wAmbaTLF54Hmu6F/F/a1W5eZC8Y/JVeU+ewiH0l7oOjnNpFnthd5Oe52oczvllJ5Y7J+TubHNArm6u3vVJ99eNQ1oLL2jEYE+OlNoCwMCxy10nvge1kiMbLpj4b+IHFyfW797OZhrdTEqyS7qt1L/9WFNJq1OHIQEEQR1FJJ/ll14j2ttNKOFNDPySUrk3V7ucR8mgwV3JbkrrG44R5NUs12uScB8UsnyK6T40W4OxO9XJkNM3JkodcWD3lm7XMPphz3f6gCSLda0i2kq66N3g8wQaQlVQz72KeOQ7b2yznVCkr9vSJmOlXOEMWEtD4cDccgsjDwPPcxKIe5jN5VxrcfxjdG5Pql6mzv0TQ9wKbs0PAm+MbgVRe31K8M= v1nh2oz4@vinh-MS-7C52
  PublicEC2AMI:
      Description: "The AMI ID to be used for the Public EC2 Instance"
      Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
      Default: '/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64'
  PublicEC2Name:
    Description: "The Name tag for the Public EC2 Instance"
    Type: String
    Default: "Devops-Public-EC2"
  PublicEC2PrivateIP:
    Description: "The static private IP address to be assigned to the Public EC2 Instance"
    Type: String
    Default: "10.0.0.4"
  PublicEC2InstanceType:
    Description: "The EC2 instance type for the Public EC2 Instance (e.g., t2.micro)"
    Type: String
    Default: "t3.micro"
  PrivateEIPName:
    Description: "The Name tag for the Elastic IP allocated for the NAT Gateway"
    Type: String
    Default: "Devops-Private-EIP"
  PrivateNatGatewayName:
    Description: "The Name tag for the Private NAT Gateway"
    Type: String
    Default: "Devops-Private-Nat-Gateway"
  PrivateRouteTableName:
    Description: "The Name tag for the Private Route Table"
    Type: String
    Default: "Private-Route-Table"
  PrivateSubnetCidrBlock:
    Description: "The IPv4 CIDR block for the Private Subnet"
    Type: String
    Default: "10.0.10.0/24"
  PrivateSubnetName:
    Description: "The Name tag for the Private Subnet"
    Type: String
    Default: "Private-Subnet"
  PrivateSecurityGroupName:
    Description: "The Name tag and Group Name for the Private Security Group"
    Type: String
    Default: "Devops-Private-Security-Group"
  PrivateEC2AMI:
    Description: "The AMI ID to be used for the Private EC2 Instance"
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64'
  PrivateEC2Name:
    Description: "The Name tag for the Private EC2 Instance"
    Type: String
    Default: "Devops-Private-EC2"
  PrivateEC2PrivateIP:
    Description: "The static private IP address to be assigned to the Private EC2 Instance"
    Type: String
    Default: "10.0.10.8"
  PrivateEC2InstanceType:
    Description: "The EC2 instance type for the Private EC2 Instance"
    Type: String
    Default: "t3.micro"
# Mappings:
  
# Conditions:
  
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VPCCidrBlock
      EnableDnsHostnames: false
      EnableDnsSupport: true
      Tags: 
        - Key: "Name"
          Value: !Ref VPCName
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags: 
        - Key: "Name"
          Value: !Ref PublicInternetGatewayName
  InternetGatewayVPCAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC # Required
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      Tags: 
        - Key: "Name"
          Value: !Ref PublicRouteTableName
      VpcId: !Ref VPC # Required
  PublicRoute:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: "0.0.0.0/0"
      GatewayId: !Ref InternetGateway
      RouteTableId: !Ref PublicRouteTable # Required
  PublicSubnet:
      Type: AWS::EC2::Subnet
      Properties:
        VpcId: !Ref VPC
        CidrBlock: !Ref PublicSubnetCidrBlock
        MapPublicIpOnLaunch: true
        AvailabilityZone: !Select [ 0, !GetAZs '' ]
        Tags: 
          - Key: "Name"
            Value: !Ref PublicSubnetName

  PublicSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable # Required
      SubnetId: !Ref PublicSubnet # Required
  PublicSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Ref PublicSecurityGroupName # Required
      GroupName: !Ref PublicSecurityGroupName
      Tags: 
        - Key: "Name"
          Value: !Ref PublicSecurityGroupName
      VpcId: !Ref VPC
  PublicSecurityGroupEgress:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      CidrIp: "0.0.0.0/0"
      Description: "Allow all egress"
      GroupId: !Ref PublicSecurityGroup # Required
      IpProtocol: "-1" # Required
  PublicSecurityGroupIngressSSH:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      CidrIp: !Ref PublicSecurityIngressUserIP
      Description: "Allow ssh from user ip"
      FromPort: 22
      GroupId: !Ref PublicSecurityGroup
      IpProtocol: "tcp" # Required
      ToPort: 22
  PublicSecurityGroupIngressPing:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      CidrIp: !Ref PublicSecurityIngressUserIP
      Description: "Allow ssh from user ip"
      FromPort: -1
      GroupId: !Ref PublicSecurityGroup
      IpProtocol: "icmp" # Required
      ToPort: -1
  Keypair:
      Type: AWS::EC2::KeyPair
      DeletionPolicy: Retain
      UpdateReplacePolicy: Retain
      Properties:
        # Sử dụng !Sub để tạo tên duy nhất: Tên_ngẫu_nhiên-Tên_Stack
        KeyName: !Sub "${KeyPairName}-${AWS::StackName}" 
        PublicKeyMaterial: !Ref KeyPairPublicKey
        Tags: 
          - Key: "Name"
            Value: !Ref KeyPairName
  PublicEC2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref PublicEC2AMI
      InstanceType: !Ref PublicEC2InstanceType
      KeyName: !Ref Keypair
      PrivateIpAddress: !Ref PublicEC2PrivateIP
      SecurityGroupIds: 
        - !Ref PublicSecurityGroup
      SubnetId: !Ref PublicSubnet
      Tags: 
        - Key: "Name"
          Value: !Ref PublicEC2Name


  PrivateEIP:
    Type: AWS::EC2::EIP
    Properties:
      Tags: 
        - Key: "Name"
          Value: !Ref PrivateEIPName

  PrivateNatGateway:
    Type: AWS::EC2::NatGateway
    Properties: 
      SubnetId: !Ref PublicSubnet
      AllocationId: !GetAtt PrivateEIP.AllocationId
      ConnectivityType: "public"
      Tags: 
        - Key: "Name"
          Value: !Ref PrivateNatGatewayName


  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      Tags: 
        - Key: "Name"
          Value: !Ref PrivateRouteTableName
      VpcId: !Ref VPC # Required
  PrivateRoute:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: "0.0.0.0/0"
      NatGatewayId: !Ref PrivateNatGateway
      RouteTableId: !Ref PrivateRouteTable # Required
  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref PrivateSubnetCidrBlock
      # Ép Private Subnet cùng AZ với Public để NAT Gateway hoạt động được
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      Tags: 
        - Key: "Name"
          Value: !Ref PrivateSubnetName
  PrivateSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PrivateRouteTable # Required
      SubnetId: !Ref PrivateSubnet # Required
  PrivateSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Ref PrivateSecurityGroupName # Required
      GroupName: !Ref PrivateSecurityGroupName
      Tags: 
        - Key: "Name"
          Value: !Ref PrivateSecurityGroupName
      VpcId: !Ref VPC
  PrivateSecurityGroupEgress:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      CidrIp: "0.0.0.0/0"
      Description: "Allow all egress"
      GroupId: !Ref PrivateSecurityGroup # Required
      IpProtocol: "-1" # Required
  PrivateSecurityGroupIngressSSH:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      SourceSecurityGroupId: !Ref PublicSecurityGroup
      Description: "Allow ssh from public secuirty group"
      FromPort: 22
      GroupId: !Ref PrivateSecurityGroup
      IpProtocol: "tcp" # Required
      ToPort: 22
  PrivateSecurityGroupIngressPing:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      SourceSecurityGroupId: !Ref PublicSecurityGroup
      Description: "Allow ssh from public secuirty group"
      FromPort: -1
      GroupId: !Ref PrivateSecurityGroup
      IpProtocol: "icmp" # Required
      ToPort: -1

  PrivateEC2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref PrivateEC2AMI
      InstanceType: !Ref PrivateEC2InstanceType
      KeyName: !Ref Keypair
      PrivateIpAddress: !Ref PrivateEC2PrivateIP
      SecurityGroupIds: 
        - !Ref PrivateSecurityGroup
      SubnetId: !Ref PrivateSubnet
      Tags: 
        - Key: "Name"
          Value: !Ref PrivateEC2Name


