name: 
on:
    push:
        paths: 'terraform/**'
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6

            - name: Setup AWS credentials
              uses: aws-actions/configure-aws-credentials@v6.1.0
              with:
                aws-region: "us-east-1"

            - name: Install terraform 
              uses: hashicorp/setup-terraform@v4
 
